apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: ${{ values.name + "igw" }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    region: ${{ values.region | dump }}
    vpcIdRef:
      name: ${{ values.name + "vpc" }}
  providerConfigRef:
    name: default